//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class insidente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insidente()
        {
            this.insidenteRespuestas = new HashSet<insidenteRespuesta>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaTomado { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public string breveDescripcion { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public Nullable<bool> problemaResuelto { get; set; }
        public Nullable<int> idPriorizacion { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public string idUsuarioCreoInsidente { get; set; }
        public string idUsuarioResolvioInsidente { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual empresaDepartamento empresaDepartamento { get; set; }
        public virtual insidenteCategoria insidenteCategoria { get; set; }
        public virtual insidentePriorizacion insidentePriorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insidenteRespuesta> insidenteRespuestas { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
