//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class insidenteRespuesta
    {
        public int idRespuesta { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
        public Nullable<bool> resolvioProblema { get; set; }
        public Nullable<bool> respuestaDeSoporte { get; set; }
        public string comentario { get; set; }
        public Nullable<int> idInsidente { get; set; }
        public string idUsuarioRespuesta { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual insidente insidente { get; set; }
    }
}
